### ISSUE TITLE
Add downgraded Doom Eternal appmanifest

### ISSUE THREAD

**Issue by lpww** [lpww/doomgrader#3]
It would be useful as a reference. There might be a copy of it already in the proton issue

**Comment by rv32ima** [comment]
The .acf file /seems/ to be very similar to JSON in it's structure, but the main things to watch out for are the StateFlags and UpdateResult inside of it. This is the file I personally have in my steamapps/ folder: https://www.0xcc.pw/files/appmanifest_782330.acf.

**Comment by lpww** [comment]
I've looked into this and I'm not sure we need the full appmanifest because it's not used anywhere and the only relevant parts seem to be the list of depots/manifests. I think a reference of each depot id and it's corresponding manifest id would be useful in the readme or as a separate file
